<script>
export default {
    name:'picker',
    data(){
        return {
            list:
            [
                [
                    {
                        label:'第一第一第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第二',
                        value:1
                    },
                    {
                        label:'第三',
                        value:2
                    },
                    {
                        label:'第四',
                        value:3
                    },
                    {
                        label:'第五',
                        value:4
                    },
                    {
                        label:'第六',
                        value:5
                    },
                    {
                        label:'第七',
                        value:6
                    },
                    {
                        label:'第八',
                        value:7
                    }
                ],
                [
                    {
                        label:'第一第一第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第一',
                        value:0
                    },
                    {
                        label:'第二',
                        value:1
                    },
                    {
                        label:'第三',
                        value:2
                    },
                    {
                        label:'第四',
                        value:3
                    },
                    {
                        label:'第五',
                        value:4
                    },
                    {
                        label:'第六',
                        value:5
                    },
                    {
                        label:'第七',
                        value:6
                    },
                    {
                        label:'第八',
                        value:7
                    }
                ]
            ],
            select:[0,0],
            event:[]
        }
    },
    methods:{
        handleChange(e,index){
            this.$set(this.event,index,e)
        },
        change(e){
            this.event = e
        }
    }
}
</script>
<template>
    <div class="container">
        <p>Picker选择器：</p>
        <div v-for="(i,k) in event "
        :key="k"
        >
            <p>选中label为：{{i.label}}</p>
            <p>选中value为:{{i.value}}</p>
        </div>
        <Picker
        :list="list"
        :select="select"
        placeholder="请选择需要的选项"
        @columeChange="handleChange"
        @change="change"
        ></Picker>
    </div>
</template>
